[package]
name           = "prometheus_wireguard_exporter"
version        = "1.2.0"
authors        = ["Francesco Cogno <francesco.cogno@outlook.com>"]
description    = "Prometheus WireGuard Exporter"
edition        = "2018"

readme         = "README.md"
license        = "MIT"
repository     = "https://github.com/MindFlavor/prometheus_wireguard_exporter"
documentation  = "https://github.com/MindFlavor/prometheus_wireguard_exporter"
homepage       = "https://github.com/MindFlavor/prometheus_wireguard_exporter"

keywords       = ["prometheus", "exporter", "wireguard"]
categories     = ["database"]


[dependencies]
log            = "*"
env_logger     = "*"
futures        = "*"
clap           = "*"
serde_json     = "*"
serde          = "*"
serde_derive   = "*"
failure        = "*"
hyper          = "*"
http           = "*"
